import { IUser } from '../types/User';

export const mockUsers: IUser[] = [
  {
    id: '1',
    email: 'danylo@example.com',
    hashedPassword: 'hashedpassword1',
    firstName: 'Danylo',
    lastName: 'Ivanov',
    phone: '+380501234567',
    role: 'student',
    profileImageUrl: '/avatars/ayPromise.png',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date(),
    lastLogin: new Date('2025-04-28'),
    completedArticles: ['article1', 'article2'],
    completedLectures: ['lecture1'],
    completedVideos: [],
    certificates: [],
  },
  {
    id: '2',
    email: 'john@example.com',
    hashedPassword: 'hashedpassword2',
    firstName: 'John',
    lastName: 'Doe',
    phone: '+380931112233',
    role: 'instructor',
    profileImageUrl: '/avatars/johnal.png',
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date(),
    lastLogin: null,
    completedArticles: [],
    completedLectures: [],
    completedVideos: [],
    certificates: ['cert1'],
  },
  {
    id: '3',
    email: 'uko@example.com',
    hashedPassword: 'hashedpassword3',
    firstName: 'Uko',
    lastName: 'Shevchenko',
    phone: '+380671234567',
    role: 'student',
    profileImageUrl: '/avatars/pouka.png',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date(),
    lastLogin: new Date('2025-04-10'),
    completedArticles: ['article3'],
    completedLectures: ['lecture2', 'lecture3'],
    completedVideos: ['video1'],
    certificates: [],
  },
  {
    id: '4',
    email: 'lisa@example.com',
    hashedPassword: 'hashedpassword4',
    firstName: 'Lisa',
    lastName: 'Mirova',
    phone: '+380991112233',
    role: 'admin',
    profileImageUrl: '/avatars/lisathelisa.png',
    createdAt: new Date('2024-09-20'),
    updatedAt: new Date(),
    lastLogin: new Date('2025-04-01'),
    completedArticles: [],
    completedLectures: [],
    completedVideos: [],
    certificates: ['cert2', 'cert3'],
  },
];
