import type { Metadata } from "next";
import "./globals.css";
import { Inter, Saira } from "next/font/google";
import TopBar from "@/components/custom/NavigationTopBar";
import SideBar from "@/components/custom/NavigationSideBar";
import Providers from "@/components/providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const saira = Saira({
  subsets: ["latin"],
  variable: "--font-saira",
});

export const metadata: Metadata = {
  title: "Головна сторінка | SPECTRE",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`antialiased ${inter.variable} flex flex-col h-screen ${saira.variable}`}
      >
        <Providers>
          <TopBar />
          <main className="flex grow justify-center">
            <SideBar />
            <div className="px-4 sm:px-12 lg:px-16 py-4 max-w-7xl flex-grow flex flex-col">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
