import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import TopBar from "@/components/custom/NavigationTopBar";
import SideBar from "@/components/custom/NavigationSideBar";
import Providers from "@/components/providers";
import getServerUser from "@/lib/auth";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "СПЕКТР",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userFromServer = await getServerUser();

  return (
    <html lang="uk">
      <body className={`antialiased ${inter.variable} flex flex-col h-screen`}>
        <Providers user={userFromServer}>
          <TopBar />
          <main className="flex grow justify-center">
            <SideBar />
            <div className="px-4 sm:px-12 lg:px-16 py-4 max-w-7xl flex-grow flex flex-col">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
