import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import TopBar from "@/components/custom/NavigationTopBar";
import SideBar from "@/components/custom/NavigationSideBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Icarus Eye",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.variable} flex flex-col h-screen`}>
        <TopBar />
        <main className="flex grow">
          <SideBar />
          <div className="px-4 sm:px-12 lg:px-16 py-4 max-w-7xl flex-grow">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
